### ISSUE TITLE
Call method when network connection is lost.

### ISSUE THREAD

**Issue by joyjiyuan** [wendellrocha/enhanced_meteorify#9]
When the network connection is lost, calling a method, what will happen?in my experiment 
it will deadlock here.If so, how to avoid that?

try{
  var result = await Meteor.call('hello',[{'firstname':'Wendell','lastname':'Rocha'}]);
  print(result);
}catch(error){
  print(error);
}

**Comment by wendellrocha** [comment]
Hello, I don't know if it would be an interesting feature for the package at the moment. In order to be able to re-call when the connection comes back, I would need to keep listening for the network state changes and cache calls/subscribes when the connection drops so I can re-do them when the connection is back to normal.

If it's interesting for you, pull requests are welcome.

**Comment by joyjiyuan** [comment]
Is there a good way to listen for network connections? The connection status of this package is unreliable. 

On the mobile side, I have to use InternetAddress.lookup; On the web side, I use http.get to implement same thing.
